### PR TITLE
A Full Integration of XGBoost and Apache Spark

### PR DESCRIPTION
**Pull request by CodingCat**
@tqchen , mind reviewing it?

### CODE REVIEW

**Comment by tqchen** [comment]
This looks great, please let me know when you want to merge it in

**Comment by CodingCat** [comment]
thanks, I will validate several functionalities in the following days and then ping you when it is ready to merge

**Comment by CodingCat** [comment]
@tqchen ,  I think it is ready to merge

**Comment by mli** [comment]
i suggest to host the scaladoc in a separate place rather than this repo. since each time you update the doc, there will be a lot of line changes. while this repo is mainly used for blogging now

**Comment by CodingCat** [comment]
I know that, 

the problem is that we have to find a place which can 
- recognize the relative paths in html files of scala/java docs
- render html files instead of displaying source code

especially the second requirement makes `http://dmlc.ml`  the only choice in our hand....

**Comment by tqchen** [comment]
Thanks, this is merged

**Pull request merged**
