### PR TITLE
Add TensorBoard post.

### PR DESCRIPTION
**Pull request by zihaolucky**
Hi @piiswrong @mli @tqchen @jermainewang @mufeili 

We've made a usable [TensorBoard](https://github.com/dmlc/tensorboard) solution for MXNet, although we have many future works to do, and the recent PR https://github.com/dmlc/tensorboard/pull/8 shows the usage. So I write a post for this :)

### CODE REVIEW

**Comment by piiswrong** [comment]
@mli @tqchen @antinucleon 
Let's merge this

**Comment by piiswrong** [comment]
I suggest you add a few render result images to it.

**Comment by zihaolucky** [comment]
Oh I get it.

**Comment by piiswrong** [comment]
copy some of the images from tutorial to post

**Pull request merged**
