### PR TITLE
Add MinPy Chinese Article [WIP]

### PR DESCRIPTION
**Pull request by lryta**
Add MinPy article.

### CODE REVIEW

**Comment by tqchen** [comment]
Do we want to host chinese version of blogposts in here? Since all the existing posts are in english, I might recommend to put an english version here, and put the chinese version elsewhere. @mli @jermainewang

**Comment by lryta** [comment]
I agree with @tqchen. We can host Chinese version on [dmlc.ml/cn]().

**Comment by tqchen** [comment]
dmlc.ml/cn sounds a good idea @lryta can you look into changes to make that happen? In the meanwhile, you can always bring this to the minpy repo. Thanks!

**Comment by lryta** [comment]
@tqchen I will make the change in the weekend, don't worry.

**Comment by jermainewang** [comment]
Do we still want this?

**Comment by lryta** [comment]
I don't think we need this anymore since another version is up. I will close this PR.

**Pull request closed without merging**
